import localFont from 'next/font/local';
import './globals.css';
import AuthProvider from '@/context/Authprovider';
import SideNav from './_components/SideNav';
import Search from './_components/Search';
import Button from './_components/Button';
import Link from 'next/link';
import { getServerSession } from 'next-auth';
import { options } from './api/auth/[...nextauth]/route';

export const metadata = {
  title: 'Online exam',
  description: 'Generated by Samer online exam ',
};

export default async function RootLayout({ children }) {
  // const session = await getServerSession(options);
  // console.log('session from server', session);
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <main className='flex gap-5 p-8 bg-[#FBF9F9]'>
            <SideNav />
            <div className='w-full'>
              <Search />

              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
